// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcAGVsRMNU2Jx6DElYUWjnBGuJUbUAHL0',
    appId: '1:856691475658:web:46ff52b5bd364d29b72033',
    messagingSenderId: '856691475658',
    projectId: 'fgpay-29f06',
    authDomain: 'fgpay-29f06.firebaseapp.com',
    storageBucket: 'fgpay-29f06.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB78THiyFf4xckpOBwbxR_8sgfDjHxEisM',
    appId: '1:856691475658:android:5349f63fa7fd4480b72033',
    messagingSenderId: '856691475658',
    projectId: 'fgpay-29f06',
    storageBucket: 'fgpay-29f06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7G-PjZzQcodkMZ4_o_BjnYJAfCGfzZTc',
    appId: '1:856691475658:ios:6b4c28606a2aa52bb72033',
    messagingSenderId: '856691475658',
    projectId: 'fgpay-29f06',
    storageBucket: 'fgpay-29f06.firebasestorage.app',
    iosBundleId: 'com.example.fgpayClean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7G-PjZzQcodkMZ4_o_BjnYJAfCGfzZTc',
    appId: '1:856691475658:ios:6b4c28606a2aa52bb72033',
    messagingSenderId: '856691475658',
    projectId: 'fgpay-29f06',
    storageBucket: 'fgpay-29f06.firebasestorage.app',
    iosBundleId: 'com.example.fgpayClean',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBb82yqo6-FHTsqSCsPumH5fUURgWrNs0',
    appId: '1:856691475658:web:428684fa03d9ec74b72033',
    messagingSenderId: '856691475658',
    projectId: 'fgpay-29f06',
    authDomain: 'fgpay-29f06.firebaseapp.com',
    storageBucket: 'fgpay-29f06.firebasestorage.app',
  );
}
